name: ocrtextz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.1
  flutter_svg: ^2.2.3
  shimmer_animation: ^2.2.2+1
  flutter_riverpod: ^3.2.0
  riverpod_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/illustration/
  fonts:
    - family: Lora
      fonts:
      - asset: assets/fonts/Lora_title.ttf
    
    - family: NotoSans
      fonts:
      - asset: assets/fonts/NotoSans_label.ttf

    - family: Nunito
      fonts:
      - asset: assets/fonts/Nunito_body.ttf
      
